name: Makefile CI

on:
  push:
    branches: [ "ci" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Copy game file
      run: cp --no-preserve=mode $METROID_FUSION_U_PATH ./metroid4.gba

    - name: Run make
      run: make dist AS=armips FLIPS=flips
