name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Copy game file
      run: cp --no-preserve=mode $METROID_FUSION_U_PATH ./metroid4.gba

    - name: Run make
      run: make dist AS=armips FLIPS=flips

    - name: Remove ROM
      run: rm ./bin/m4rs.gba

    - name: Upload patches as artifacts
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4.0.0
      with:
        name: Fusion Patches
        if-no-files-found: error
        path: |
          ./bin/*.ips
          ./bin/*.bps

    # TODO: upload releases on tag? would require setting DEBUG to false.

      
